name: Hello
on: push
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, world!"
            - run: echo "This is a test workflow."
            - uses: actions/checkout@v4